spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: "0000"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: info
    com.cijee: debug
  file:
    path: log/blog-dev